import postgres from 'postgres';

// URL com senha encoded (% para caracteres especiais)
const connectionString = process.env.DATABASE_URL || 'postgresql://postgres:Pietr%40Auror%402017@db.wlmhtuqbzyethknlggwg.supabase.co:5432/postgres';
const sql = postgres(connectionString, { ssl: 'require' });

const DDL = `
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS USUARIO (
  ID_USUARIO UUID PRIMARY KEY,
  NOME TEXT NOT NULL DEFAULT 'NOVO USUARIO',
  EMAIL TEXT NOT NULL UNIQUE,
  TELEFONE TEXT,
  PLANO TEXT NOT NULL DEFAULT 'FREE',
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  DATA_CADASTRO TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS AGENDA (
  ID_AGENDA UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_USUARIO UUID NOT NULL,
  NOME TEXT NOT NULL DEFAULT 'MINHA AGENDA',
  COR TEXT,
  ATIVA BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT FK_AGENDA_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPROMISSO (
  ID_COMPROMISSO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_AGENDA UUID NOT NULL,
  TITULO TEXT NOT NULL,
  DESCRICAO TEXT,
  LOCAL TEXT,
  DATA_INICIO TIMESTAMP WITH TIME ZONE NOT NULL,
  DATA_FIM TIMESTAMP WITH TIME ZONE NOT NULL,
  ORIGEM TEXT NOT NULL DEFAULT 'MANUAL',
  CRIADO_POR UUID NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'ATIVO',
  DATA_CADASTRO TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_COMPROMISSO_AGENDA
    FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID_AGENDA) ON DELETE CASCADE,
  CONSTRAINT FK_COMPROMISSO_CRIADOR
    FOREIGN KEY (CRIADO_POR) REFERENCES USUARIO(ID_USUARIO) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS LEMBRETE (
  ID_LEMBRETE UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_COMPROMISSO UUID NOT NULL,
  TIPO TEXT NOT NULL DEFAULT 'PUSH',
  ANTECEDENCIA_MINUTOS INTEGER NOT NULL DEFAULT 60,
  ENVIADO BOOLEAN NOT NULL DEFAULT FALSE,
  DATA_ENVIO TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FK_LEMBRETE_COMPROMISSO
    FOREIGN KEY (ID_COMPROMISSO) REFERENCES COMPROMISSO(ID_COMPROMISSO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPARTILHAMENTO_AGENDA (
  ID_COMPARTILHAMENTO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_AGENDA UUID NOT NULL,
  ID_USUARIO_CONVIDADO UUID NOT NULL,
  PERMISSAO TEXT NOT NULL DEFAULT 'VISUALIZAR',
  STATUS TEXT NOT NULL DEFAULT 'PENDENTE',
  DATA_CONVITE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_COMPART_AGENDA
    FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(ID_AGENDA) ON DELETE CASCADE,
  CONSTRAINT FK_COMPART_CONVIDADO
    FOREIGN KEY (ID_USUARIO_CONVIDADO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
  CONSTRAINT UK_COMPART_UNICO UNIQUE (ID_AGENDA, ID_USUARIO_CONVIDADO)
);

CREATE TABLE IF NOT EXISTS COMPROMISSO_LINK (
  ID_LINK UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_COMPROMISSO UUID NOT NULL,
  TOKEN TEXT NOT NULL UNIQUE,
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  EXPIRA_EM TIMESTAMP WITH TIME ZONE,
  CRIADO_EM TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_LINK_COMPROMISSO
    FOREIGN KEY (ID_COMPROMISSO) REFERENCES COMPROMISSO(ID_COMPROMISSO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DISPOSITIVO_PUSH (
  ID_DISPOSITIVO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_USUARIO UUID NOT NULL,
  PROVIDER TEXT NOT NULL DEFAULT 'MOCK',
  TOKEN_PUSH TEXT NOT NULL,
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  CRIADO_EM TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_PUSH_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NOTIFICACAO (
  ID_NOTIFICACAO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_USUARIO UUID,
  ID_COMPROMISSO UUID,
  CANAL TEXT NOT NULL DEFAULT 'PUSH',
  STATUS TEXT NOT NULL DEFAULT 'PENDENTE',
  PAYLOAD_JSON JSONB,
  ERRO TEXT,
  CRIADO_EM TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  ENVIADO_EM TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FK_NOTIF_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL,
  CONSTRAINT FK_NOTIF_COMPROMISSO
    FOREIGN KEY (ID_COMPROMISSO) REFERENCES COMPROMISSO(ID_COMPROMISSO) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS WHATSAPP_LOG (
  ID_LOG UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_USUARIO UUID,
  TIPO TEXT NOT NULL,
  TELEFONE TEXT,
  TEXTO TEXT,
  PAYLOAD_JSON JSONB,
  CRIADO_EM TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_WA_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS SOLICITACAO_IA (
  ID_SOLICITACAO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  ID_USUARIO UUID NOT NULL,
  ORIGEM TEXT NOT NULL DEFAULT 'TEXTO',
  ENTRADA_TEXTO TEXT NOT NULL,
  STATUS TEXT NOT NULL DEFAULT 'PENDENTE',
  SAIDA_JSON JSONB,
  ERRO TEXT,
  CRIADO_EM TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_IA_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_AGENDA_ID_USUARIO ON AGENDA (ID_USUARIO);
CREATE INDEX IF NOT EXISTS IDX_COMPROMISSO_ID_AGENDA ON COMPROMISSO (ID_AGENDA);
CREATE INDEX IF NOT EXISTS IDX_COMPROMISSO_DATA_INICIO ON COMPROMISSO (DATA_INICIO);
CREATE INDEX IF NOT EXISTS IDX_COMPART_CONVIDADO ON COMPARTILHAMENTO_AGENDA (ID_USUARIO_CONVIDADO);
CREATE INDEX IF NOT EXISTS IDX_LEMBRETE_PENDENTE ON LEMBRETE (ENVIADO, DATA_ENVIO);
CREATE INDEX IF NOT EXISTS IDX_NOTIF_STATUS ON NOTIFICACAO (STATUS, CRIADO_EM);
`;

const RLS = `
ALTER TABLE USUARIO ENABLE ROW LEVEL SECURITY;
ALTER TABLE AGENDA ENABLE ROW LEVEL SECURITY;
ALTER TABLE COMPROMISSO ENABLE ROW LEVEL SECURITY;
ALTER TABLE LEMBRETE ENABLE ROW LEVEL SECURITY;
ALTER TABLE COMPARTILHAMENTO_AGENDA ENABLE ROW LEVEL SECURITY;
ALTER TABLE COMPROMISSO_LINK ENABLE ROW LEVEL SECURITY;
ALTER TABLE DISPOSITIVO_PUSH ENABLE ROW LEVEL SECURITY;
ALTER TABLE NOTIFICACAO ENABLE ROW LEVEL SECURITY;
ALTER TABLE WHATSAPP_LOG ENABLE ROW LEVEL SECURITY;
ALTER TABLE SOLICITACAO_IA ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS USUARIO_SELECT_PROPRIO ON USUARIO;
DROP POLICY IF EXISTS USUARIO_UPDATE_PROPRIO ON USUARIO;
DROP POLICY IF EXISTS USUARIO_INSERT_PROPRIO ON USUARIO;
CREATE POLICY USUARIO_SELECT_PROPRIO ON USUARIO FOR SELECT USING (ID_USUARIO = auth.uid());
CREATE POLICY USUARIO_UPDATE_PROPRIO ON USUARIO FOR UPDATE USING (ID_USUARIO = auth.uid());
CREATE POLICY USUARIO_INSERT_PROPRIO ON USUARIO FOR INSERT WITH CHECK (ID_USUARIO = auth.uid());

DROP POLICY IF EXISTS AGENDA_SELECT ON AGENDA;
DROP POLICY IF EXISTS AGENDA_INSERT ON AGENDA;
DROP POLICY IF EXISTS AGENDA_UPDATE ON AGENDA;
DROP POLICY IF EXISTS AGENDA_DELETE ON AGENDA;
CREATE POLICY AGENDA_SELECT ON AGENDA FOR SELECT USING (
  ID_USUARIO = auth.uid()
  OR EXISTS (SELECT 1 FROM COMPARTILHAMENTO_AGENDA CA WHERE CA.ID_AGENDA = AGENDA.ID_AGENDA AND CA.ID_USUARIO_CONVIDADO = auth.uid() AND CA.STATUS = 'ACEITO')
);
CREATE POLICY AGENDA_INSERT ON AGENDA FOR INSERT WITH CHECK (ID_USUARIO = auth.uid());
CREATE POLICY AGENDA_UPDATE ON AGENDA FOR UPDATE USING (ID_USUARIO = auth.uid());
CREATE POLICY AGENDA_DELETE ON AGENDA FOR DELETE USING (ID_USUARIO = auth.uid());

DROP POLICY IF EXISTS COMPROMISSO_SELECT ON COMPROMISSO;
DROP POLICY IF EXISTS COMPROMISSO_INSERT ON COMPROMISSO;
DROP POLICY IF EXISTS COMPROMISSO_UPDATE ON COMPROMISSO;
DROP POLICY IF EXISTS COMPROMISSO_DELETE ON COMPROMISSO;
CREATE POLICY COMPROMISSO_SELECT ON COMPROMISSO FOR SELECT USING (
  EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = COMPROMISSO.ID_AGENDA AND (A.ID_USUARIO = auth.uid() OR EXISTS (SELECT 1 FROM COMPARTILHAMENTO_AGENDA CA WHERE CA.ID_AGENDA = A.ID_AGENDA AND CA.ID_USUARIO_CONVIDADO = auth.uid() AND CA.STATUS = 'ACEITO')))
);
CREATE POLICY COMPROMISSO_INSERT ON COMPROMISSO FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = ID_AGENDA AND (A.ID_USUARIO = auth.uid() OR EXISTS (SELECT 1 FROM COMPARTILHAMENTO_AGENDA CA WHERE CA.ID_AGENDA = A.ID_AGENDA AND CA.ID_USUARIO_CONVIDADO = auth.uid() AND CA.STATUS = 'ACEITO' AND CA.PERMISSAO = 'EDITAR'))) AND CRIADO_POR = auth.uid());
CREATE POLICY COMPROMISSO_UPDATE ON COMPROMISSO FOR UPDATE USING (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = COMPROMISSO.ID_AGENDA AND (A.ID_USUARIO = auth.uid() OR EXISTS (SELECT 1 FROM COMPARTILHAMENTO_AGENDA CA WHERE CA.ID_AGENDA = A.ID_AGENDA AND CA.ID_USUARIO_CONVIDADO = auth.uid() AND CA.STATUS = 'ACEITO' AND CA.PERMISSAO = 'EDITAR'))));
CREATE POLICY COMPROMISSO_DELETE ON COMPROMISSO FOR DELETE USING (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = COMPROMISSO.ID_AGENDA AND A.ID_USUARIO = auth.uid()));

DROP POLICY IF EXISTS LEMBRETE_SELECT ON LEMBRETE;
DROP POLICY IF EXISTS LEMBRETE_INSERT ON LEMBRETE;
DROP POLICY IF EXISTS LEMBRETE_UPDATE ON LEMBRETE;
DROP POLICY IF EXISTS LEMBRETE_DELETE ON LEMBRETE;
CREATE POLICY LEMBRETE_SELECT ON LEMBRETE FOR SELECT USING (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = LEMBRETE.ID_COMPROMISSO AND (A.ID_USUARIO = auth.uid() OR EXISTS (SELECT 1 FROM COMPARTILHAMENTO_AGENDA CA WHERE CA.ID_AGENDA = A.ID_AGENDA AND CA.ID_USUARIO_CONVIDADO = auth.uid() AND CA.STATUS = 'ACEITO' AND CA.PERMISSAO = 'EDITAR'))));
CREATE POLICY LEMBRETE_INSERT ON LEMBRETE FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = ID_COMPROMISSO AND (A.ID_USUARIO = auth.uid() OR EXISTS (SELECT 1 FROM COMPARTILHAMENTO_AGENDA CA WHERE CA.ID_AGENDA = A.ID_AGENDA AND CA.ID_USUARIO_CONVIDADO = auth.uid() AND CA.STATUS = 'ACEITO' AND CA.PERMISSAO = 'EDITAR'))));
CREATE POLICY LEMBRETE_UPDATE ON LEMBRETE FOR UPDATE USING (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = LEMBRETE.ID_COMPROMISSO AND A.ID_USUARIO = auth.uid()));
CREATE POLICY LEMBRETE_DELETE ON LEMBRETE FOR DELETE USING (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = LEMBRETE.ID_COMPROMISSO AND A.ID_USUARIO = auth.uid()));

DROP POLICY IF EXISTS COMPART_SELECT ON COMPARTILHAMENTO_AGENDA;
DROP POLICY IF EXISTS COMPART_INSERT ON COMPARTILHAMENTO_AGENDA;
DROP POLICY IF EXISTS COMPART_UPDATE ON COMPARTILHAMENTO_AGENDA;
DROP POLICY IF EXISTS COMPART_DELETE ON COMPARTILHAMENTO_AGENDA;
CREATE POLICY COMPART_SELECT ON COMPARTILHAMENTO_AGENDA FOR SELECT USING (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = COMPARTILHAMENTO_AGENDA.ID_AGENDA AND (A.ID_USUARIO = auth.uid() OR COMPARTILHAMENTO_AGENDA.ID_USUARIO_CONVIDADO = auth.uid())));
CREATE POLICY COMPART_INSERT ON COMPARTILHAMENTO_AGENDA FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = ID_AGENDA AND A.ID_USUARIO = auth.uid()));
CREATE POLICY COMPART_UPDATE ON COMPARTILHAMENTO_AGENDA FOR UPDATE USING (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = COMPARTILHAMENTO_AGENDA.ID_AGENDA AND (A.ID_USUARIO = auth.uid() OR COMPARTILHAMENTO_AGENDA.ID_USUARIO_CONVIDADO = auth.uid())));
CREATE POLICY COMPART_DELETE ON COMPARTILHAMENTO_AGENDA FOR DELETE USING (EXISTS (SELECT 1 FROM AGENDA A WHERE A.ID_AGENDA = COMPARTILHAMENTO_AGENDA.ID_AGENDA AND A.ID_USUARIO = auth.uid()));

DROP POLICY IF EXISTS LINK_SELECT ON COMPROMISSO_LINK;
DROP POLICY IF EXISTS LINK_INSERT ON COMPROMISSO_LINK;
DROP POLICY IF EXISTS LINK_UPDATE ON COMPROMISSO_LINK;
DROP POLICY IF EXISTS LINK_DELETE ON COMPROMISSO_LINK;
CREATE POLICY LINK_SELECT ON COMPROMISSO_LINK FOR SELECT USING (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = COMPROMISSO_LINK.ID_COMPROMISSO AND A.ID_USUARIO = auth.uid()));
CREATE POLICY LINK_INSERT ON COMPROMISSO_LINK FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = ID_COMPROMISSO AND A.ID_USUARIO = auth.uid()));
CREATE POLICY LINK_UPDATE ON COMPROMISSO_LINK FOR UPDATE USING (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = COMPROMISSO_LINK.ID_COMPROMISSO AND A.ID_USUARIO = auth.uid()));
CREATE POLICY LINK_DELETE ON COMPROMISSO_LINK FOR DELETE USING (EXISTS (SELECT 1 FROM COMPROMISSO C JOIN AGENDA A ON A.ID_AGENDA = C.ID_AGENDA WHERE C.ID_COMPROMISSO = COMPROMISSO_LINK.ID_COMPROMISSO AND A.ID_USUARIO = auth.uid()));

DROP POLICY IF EXISTS PUSH_SELECT ON DISPOSITIVO_PUSH;
DROP POLICY IF EXISTS PUSH_INSERT ON DISPOSITIVO_PUSH;
DROP POLICY IF EXISTS PUSH_UPDATE ON DISPOSITIVO_PUSH;
DROP POLICY IF EXISTS PUSH_DELETE ON DISPOSITIVO_PUSH;
CREATE POLICY PUSH_SELECT ON DISPOSITIVO_PUSH FOR SELECT USING (ID_USUARIO = auth.uid());
CREATE POLICY PUSH_INSERT ON DISPOSITIVO_PUSH FOR INSERT WITH CHECK (ID_USUARIO = auth.uid());
CREATE POLICY PUSH_UPDATE ON DISPOSITIVO_PUSH FOR UPDATE USING (ID_USUARIO = auth.uid());
CREATE POLICY PUSH_DELETE ON DISPOSITIVO_PUSH FOR DELETE USING (ID_USUARIO = auth.uid());

DROP POLICY IF EXISTS NOTIF_SELECT ON NOTIFICACAO;
CREATE POLICY NOTIF_SELECT ON NOTIFICACAO FOR SELECT USING (ID_USUARIO = auth.uid());

DROP POLICY IF EXISTS IA_SELECT ON SOLICITACAO_IA;
DROP POLICY IF EXISTS IA_INSERT ON SOLICITACAO_IA;
CREATE POLICY IA_SELECT ON SOLICITACAO_IA FOR SELECT USING (ID_USUARIO = auth.uid());
CREATE POLICY IA_INSERT ON SOLICITACAO_IA FOR INSERT WITH CHECK (ID_USUARIO = auth.uid());
`;

async function setup() {
  try {
    console.log('🔄 Criando tabelas...');
    const statements = DDL.split(';').filter(s => s.trim());
    for (const stmt of statements) {
      if (stmt.trim()) {
        try {
          await sql.unsafe(stmt);
        } catch (e) {
          if (e.message.includes('already exists')) {
            console.log('⚠️  Tabela já existe');
          } else {
            throw e;
          }
        }
      }
    }
    console.log('✅ Tabelas criadas!');

    console.log('🔄 Criando RLS policies...');
    const rlsLines = RLS.split('\n').filter(s => s.trim() && !s.trim().startsWith('--'));
    let currentStmt = '';
    
    for (const line of rlsLines) {
      currentStmt += ' ' + line;
      if (line.includes(';')) {
        const stmt = currentStmt.trim();
        if (stmt && stmt !== ';') {
          try {
            await sql.unsafe(stmt);
          } catch (e) {
            if (e.message.includes('already exists')) {
              // Policy já existe, ignora
            } else {
              console.error('Erro em statement:', stmt.substring(0, 50) + '...');
              throw e;
            }
          }
        }
        currentStmt = '';
      }
    }
    console.log('✅ RLS policies criadas!');

    console.log('\n✨ Setup completo! Banco pronto para usar.');
    process.exit(0);
  } catch (error) {
    console.error('❌ Erro:', error.message);
    process.exit(1);
  }
}

setup();
